// NexDev Homepage — Minimal JS
// Generated by salecraft.plugin homepage-builder skill

// Smooth scroll
document.querySelectorAll('a[href^="#"]').forEach(a => {
  a.addEventListener('click', e => {
    e.preventDefault();
    const target = document.querySelector(a.getAttribute('href'));
    if (target) {
      target.scrollIntoView({ behavior: 'smooth' });
      // Close mobile menu if open
      document.querySelector('.nav-links')?.classList.remove('active');
    }
  });
});

// Mobile menu toggle
const menuBtn = document.querySelector('.menu-toggle');
const nav = document.querySelector('.nav-links');
menuBtn?.addEventListener('click', () => nav?.classList.toggle('active'));

// Lazy loading fallback for older browsers
if ('IntersectionObserver' in window) {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const el = entry.target;
        if (el.dataset.src) {
          el.src = el.dataset.src;
          observer.unobserve(el);
        }
      }
    });
  }, { rootMargin: '200px' });
  document.querySelectorAll('img[data-src], iframe[data-src]').forEach(el => observer.observe(el));
}
